# Day 1
## 1.1 ndarray 구조 이해
- ndarray(N-dimensional array)는 NumPy의 핵심 객체
- 모든 원소의 타입이 동일(자바 배열과 동일)
- 메모리 + 메타데이터 구조체  

In [17]:
# %pip install --upgrade pip
# %pip install np

import numpy as np

# 실제론 [1,2,3,4,5,6] 이렇게 저장됨. CPU캐시 친화적
arr = np.array([[1,2,3],
                [4,5,6]])

arr.shape # (2, 3) 2행 3열        


(2, 3)

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])

arr.strides # (24, 8) int64(8바이트)의 경우, 다음 행으로 가려면 24(=8*3), 옆칸은 8

(24, 8)

In [20]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr.dtype # arr요소의 타입 확인

dtype('int64')

In [33]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr.ndim # 배열의 차원수

2

In [31]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr.size # 모든 요소의 개수

6

## 1.2 ndarray 생성 방법
- array()는 가장 기본적인 생성방법
- ndarray()도 가능하지만, 저수준(수동처리)이라 거의 사용x  
C extension 만들 때  
메모리 버퍼 직접 다룰 때  
shared memory 연결할 때  
매우 저수준 최적화할 때   

In [ ]:
a = np.array([1, 2, 3])            # 1차원 numpy.ndarray타입
b = np.array([[1, 2], [3, 4]])     # 2차원
c = np.array([1, 2, 3], dtype=np.float64) # 배열 요소의 타입 지정
c

array([1., 2., 3.])

In [154]:
b = np.array([1, 2, 3], ndmin=3)  # 최소 차원 지정
b

array([[[1, 2, 3]]])

### 타입 변환(있는 객체를 배열로)
- np.asarray(obj) : 이미 ndarray이면 복사하지 않음(가능하면), 일반 시퀀스면 새로 생성.
- np.array(obj) : 항상 ndarray로 만들기 위해 복사될 수 있음.

In [ ]:
lst = [1,2,3]
x1 = np.asarray(lst)   # 보통 복사 안 됨
x2 = np.array(lst)     # 새 배열
lst[0] = 9
print(f"{lst=}")
print(f"{x1=}")
print(f"{x2=}")

lst=[9, 2, 3]
x1=array([1, 2, 3])
x2=array([1, 2, 3])


### 범위 기반 생성: arange, linspace
- range는 부동소수점 스텝에서 오차문제(누락/초과)가 있을 수 있으므로 실수 범위에선 linspace 

In [56]:
np.arange(0, 10, 2)       # [0 2 4 6 8]  range()와 유사
np.linspace(0, 1, 5)      # [0.   0.25 0.5  0.75 1.  ]  # 등간격 5개

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 값이 채워진 배열: zeros, ones, full, empty
- empty는 초기화 비용 없어서 빠르지만 값은 쓰기 전까지 신뢰할 수 없음.

In [118]:
np.zeros((2,3))          # 2x3배열. 모든 원소 0
np.ones(5, dtype=int)    # [1,1,1,1,1] 정수 1로 채움
np.full((3,3), 7)        # 3x3을 7로 채움
np.empty((2,2))          # 2x2 초기화되지 않은 임의의 값(성능 목적). 수동 초기화

array([[-1.37223896e-071, -2.09977476e-143],
       [-1.30552615e-276,  4.33759310e-215]])

### 항등/대각행렬

In [ ]:
np.eye(4)                # 단위 행렬 (float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity(3)           # 항등 행렬(=단위 행렬)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.diag([1,2,3])         # 대각 행렬

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### 정렬된 그리드/좌표: meshgrid, mgrid

In [ ]:
x = np.linspace(0,1,3) # [0, 0.5, 1]
y = np.linspace(0,1,2) # [0, 1]

X, Y = np.meshgrid(x, y)   # 좌표 그리드 (2차원)
# np.mgrid도 사용 가능: np.mgrid[0:3, 0:2] -> 정수 인덱스 그리드
print(f"{X=}")
print(f"{Y=}")

# 0:3 -> 0,1,2
# 0:2 -> 0,1
X, Y = np.mgrid[0:3, 0:2]   # 좌표 그리드 (2차원)
print(f"{X=}")
print(f"{Y=}")

X=array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])
Y=array([[0., 0., 0.],
       [1., 1., 1.]])
X=array([[0, 0],
       [1, 1],
       [2, 2]])
Y=array([[0, 1],
       [0, 1],
       [0, 1]])


### 난수 배열 생성 : random()
- 권장: 새로운 Generator API 사용 np.random.default_rng() — 재현성/성능/안정성 우수

In [100]:
rng = np.random.default_rng(123)
rng.random((2,3))         # 균등 [0,1)
rng.normal(loc=0, scale=1, size=(3,3))  # 정규분포
rng.integers(0, 10, size=5)             # 0~9 정수

array([1, 6, 4, 9, 7])

### 파일/버퍼로부터: fromfile(), frombuffer(), loadtxt()

In [84]:
%%writefile data.bin
# 바이너리 파일에서 직접 읽기(형식 맞아야 함)
arr = np.fromfile('data.bin', dtype=np.float32)

# 파이썬 바이트 버퍼로부터
buf = b'\x01\x00\x00\x00' * 4
np.frombuffer(buf, dtype=np.int32)

# 텍스트 CSV 등은 np.loadtxt, np.genfromtxt 또는 pandas 사용 권장

Writing data.bin


### 반복 생성: tile(), repeat()

In [82]:
a = np.array([1,2])
np.tile(a, 3)     # [1 2 1 2 1 2]
np.repeat(a, 2)   # [1 1 2 2]

array([1, 1, 2, 2])

### 여러 배열 연결
- concatenate() : 앞뒤로 붙여서 하나로 연결
- vstack() : 위아래로(vertical) 쌓아서 하나로 연결
- hstack() : 좌우로(horizontal) 썋아서 하나로 연결

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
np.concatenate([a,b])      # [1 2 3 4]
np.vstack([a,b])           # [[1 2]
                           #  [3 4]]
np.hstack([a,b])           # [1 2 3 4]

# 수직축(axis=0)인지, 수평축(axis=1)인지 지정 
print(np.stack([a,b], axis=0)) # [[1,2]
                               #  [3,4]]
print(np.stack([a,b], axis=1)) # [[1,3]
                               #  [2,4]]

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### 슬라이싱/뷰 vs 복사
- 배열 슬라이스는 뷰(view) 를 반환하는 경우가 많아 원본을 변경하면 슬라이스도 바뀜

In [73]:
x = np.arange(10) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y  = x[0:5]       # [0, 1, 2, 3, 4] 슬라이싱(0~4, 5는 미포함)
y2 = x[0:5].copy() # 깊은 복사
y[0] = 999

# y를 변경했으나, x도 변경됨: 
print(f"{x[0] == 999}") # True
print(f"{y2[0]== 999}") # False

True
False


### 🔍 슬라이싱이 빠른 이유  
이때 데이터 복사 안 일어남. 메타 데이터만 수정
- data 그대로
- shape 변경
- strides 변경

In [39]:
# 슬라이싱 예제 넣을 것

### view() vs. copy()

In [29]:
arr = np.array([1,2,3])
arr2 = arr.view() # 얕은 복사(참조만 복사)
arr3 = arr.copy() # 깊은 복사(내용 복사)

print(f"{arr=}")
print(f"{arr2=}")
print(f"{arr3=}")
arr[0] = 0
print(f"{arr=}")
print(f"{arr2=}")
print(f"{arr3=}")

arr=array([1, 2, 3])
arr2=array([1, 2, 3])
arr3=array([1, 2, 3])
arr=array([0, 2, 3])
arr2=array([0, 2, 3])
arr3=array([1, 2, 3])


## 1.3 ndarray 변환

### reshape - 해석 방식을 바꾸는 것(shape와 strides를 다시 계산)
- reshape()전과 후의 요소 개수가 동일 해야함
- (1,12)은 (2,6), (3,4), (4,3), (6,2), (12,1)로 변환가능
- 차원의 길이를 지정하지 않고, -1로 주면 자동 계산

In [ ]:
import numpy as np

arr = np.arange(6) # 1 x 6
print(f"{arr=}")

# 해석 방법만 바꿀 뿐, 변경x
arr2 = arr.reshape(2,3) # 1 x 6 -> 2 x 3    1*6 == 2*3이 True이어야
print(f"{arr2=}")

arr=array([0, 1, 2, 3, 4, 5])
arr2=array([[0, 1, 2],
       [3, 4, 5]])


In [2]:
arr = np.arange(8) # 1 x 8
print(f"{arr=}")
arr2 = arr.reshape(2, -1)  # -1은 나머지 차원을 자동 계산하라는 의미.
print(f"{arr2=}")

# (1,8) -> (2,4)
# arr2=array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

arr=array([0, 1, 2, 3, 4, 5, 6, 7])
arr2=array([[0, 1, 2, 3],
       [4, 5, 6, 7]])


In [3]:
import numpy as np

arr = np.arange(6) # 1 x 6  [0,1,2,3,4,5,6]
print(f"{arr.strides}")  # (8,) 다음 요소로 가려면 8 byte
# 해석 방법만 바꿀 뿐, 변경x
arr2 = arr.reshape(2,3) # 1 x 6 -> 2 x 3    1*6 == 2*3이 True이어야
print(f"{arr2.strides}")  # (24, 8) 다음 행 이동은 24 byte, 다음 요소는 8 byte

(8,)
(24, 8)


### flatten(항상 복사) vs. ravel(가능하면 뷰)
- 원본 절대 보호해야 하면 → flatten()
-  성능/메모리 중요하면 → ravel()
- 실무에서는 보통 ravel() 많이 씀
- ravel도 불연속적인 메모리(2차원 배열)의 경우 복사 발생

In [113]:
a = np.arange(6)        # [0,1,2,3,4,5]
b = a.reshape((2,3))    # [0,1,2]
                        # [3,4,5] 
r = b.ravel()           # 뷰(가능하면)
print(f"{r=}")
f = b.flatten()         # 항상 복사
print(f"{f=}")
# b.T                   # 전치(transpose)
b.transpose()           # 위와 동일

r=array([0, 1, 2, 3, 4, 5])
f=array([0, 1, 2, 3, 4, 5])


array([[0, 3],
       [1, 4],
       [2, 5]])

자료형(dtypes) 변환
- 자주 쓰는 dtype: np.int8, np.int16, np.int32, np.int64,   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.uint8, np.uint16, np.uint32, np.uint64,    
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; np.float16, np.float32, np.float64,  
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; np.bool_, 

In [148]:
a = np.array([1,2,3], dtype=np.uint8)
a.astype(np.float32)   # 명시적 변환 (새 배열) # uint8 -> float32

array([1., 2., 3.], dtype=float32)

### 구조화된 배열 (record / structured arrays)
- 컬럼별 다른 타입을 갖는 배열:

In [117]:
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
data = np.array([('Alice', 25, 55.0), ('Bob', 30, 80.2)], dtype=dt)
# 필드 접근: data['name'], data['age']
data['name']

array(['Alice', 'Bob'], dtype='<U10')

### 마스킹 배열
- np.ma 모듈 사용: 결측값이나 마스킹이 필요할 때.

In [128]:
m = np.ma.array([1,2,3], mask=[False, True, False]) # True인 값을 masking
print(f"{m[0]}")
print(f"{m[1]}")   # masking되어 값이 가려짐.
print(f"{m[2]}")
m.data

1
--
3


array([1, 2, 3])

###  list vs numpy array 차이

[PyObject*, PyObject*, ...] # list는 참조변수 배열  
[1][2][3][4] (raw memory)   # ndarray는 기본형 배열  

| 항목     | list      | ndarray |
| ------ | --------- | ------- |
| 타입     | 객체 포인터 배열 | 연속 메모리  |
| 타입 통일성 | ❌         | ✅       |
| 연산 속도  | 느림        | 매우 빠름   |
| 벡터화    | ❌         | ✅       |



## 1.4 numpy 기본 연산

### 요소별(Element-wise) 연산
- NumPy 배열 간의 연산은 기본적으로 같은 위치의 요소끼리 한꺼번에 연산

| 연산  | 연산자  | 함수                              |
| --- | ---- | ------------------------------- |
| 덧셈  | `+`  | `np.add()`                      |
| 뺄셈  | `-`  | `np.subtract()`                 |
| 곱셈  | `*`  | `np.multiply()`                 |
| 행렬곱  | `@`  | `np.dot()`                 |
| 나눗셈 | `/`  | `np.divide()`                   |
| 제곱  | `**` | `np.power()`                    |
| 나머지 | `%`  | `np.mod()` ([programiz.com][1]) |


In [155]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # array([5, 7, 9])
print(a * b)   # array([ 4, 10, 18])
print(a / b)   # array([0.25, 0.4 , 0.5 ])

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [183]:
# 행렬곱은 A가 (m,3)이면 B는 (3,n)이어야 함. 결과는 m x n
a = np.array([[1, 1, 1],[2,2,2]])   # 2x3
b = np.array([[1,1,1],[2,2,2],[3,3,3]])   # 3x3
a@b # 2x3 @ 3x3 -> 2x3
# np.dot(a,b) # 위와 동일     

array([[ 6,  6,  6],
       [12, 12, 12]])

## 1.5 부가적인 배열 연산 - 통계연산

- NumPy는 기본적인 통계값 계산도 제공
- mean(), std(), var()

In [189]:
arr = np.array([1, 3, 5, 7])
print(arr.sum())   # 총합
# print(arr.avg())   # 없음
print(arr.mean())  # 평균
print(arr.max())   # 최댓값
print(arr.min())   # 최솟값
print(arr.std())   # 표준편차
print(arr.var())   # 분산

16
4.0
7
1
2.23606797749979
5.0


## 1.6 전치, 역행렬, 행렬식
| 연산                  | 의미       |
| ------------------- | -------- |
| `*`                 | 요소별 곱    |
| `@`                 | 행렬 곱     |
| `.T`                | 전치       |
| `np.linalg.det(A)`   | 행렬식      |
| `np.linalg.inv(A)`   | 역행렬      |
| `np.linalg.solve(A, b)` | 연립방정식 풀이(Ax = b) |
| `np.linalg.eig(A)` | 고유값(eigen value)/고유 벡터(eigen vector) |

In [173]:
a = np.array([[1,2,3],
              [4,5,6]])
a.T  # (2,3) -> (3,2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [176]:
a = np.array([[11,12],    # 정방행렬(n x n) 이어야 함
              [21,22]])
np.linalg.inv(a)

array([[-2.2,  1.2],
       [ 2.1, -1.1]])

In [177]:
a = np.array([[11,12],    # 정방행렬(n x n) 이어야 함
              [21,22]])
np.linalg.det(a)

np.float64(-10.000000000000037)

In [179]:
a = np.array([[11,12],    # 정방행렬(n x n) 이어야 함
              [21,22]])
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.30029762, 33.30029762]), eigenvectors=array([[-0.72801285, -0.47385942],
       [ 0.68556349, -0.88060051]]))

## 1.7 브로드 캐스팅
- 브로드캐스팅은 형상이 다른 배열끼리 연산할 때 자동으로 크기를 맞춰주는 규칙
- 반복문 없이 벡터화(빠름). 메모리 복사안하고 가상 확장
- 두 배열의 차원(shape)를 오른쪽부터 비교  
 -> 
차원이 같거나 둘 중 하나가 1이면, 연산 가능  

In [58]:
import numpy as np

a = np.array([1,2,3])
b = 2
print(a + b)  # array([3, 4, 5])

[3 4 5]


In [ ]:
# broadcasting이 되는 경우, b가 자동으로 (3,4)처럼 확장후 연산
a = np.array([1,2,3])
b = np.array([4]) # [4] -> [4,4,4]로 브로드 캐스팅
print(a + b) # [5 6 7]

[5 6 7]


In [169]:
# broadcasting이 안되는 경우
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    ])
b = np.array([1,1,1]) # 브로드 캐스팅 불가. [1] 또는 [1,1,1,1]은 가능
print(a + b) # [5 6 7]

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

## 1.8 인덱싱 / 슬라이싱

### boolean indexing
- 조건식 결과(True/False 배열)로 필터링하는 방식
- 같은 shape의 boolean 배열이 필요
- 조건 기반 필터링에 최적
- 결과는 항상 1차원으로 flatten됨 (원본 차원 유지 X)

In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

mask = arr > 25
print(mask)
# [False False  True  True  True]

print(arr[mask])
# [30 40 50]

[False False  True  True  True]
[30 40 50]


In [10]:
arr = np.array([[1,2],
                [3,4]])

print(arr[arr > 2]) # 조건(arr>2)에 맞는 요소만으로 배열(1차원) 구성

[3 4]


In [15]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr > np.array([2,2,2])) # broadcasting후, boolean indexing


[[False False  True]
 [ True  True  True]]


In [46]:
arr = np.arange(12).reshape(3,4) # [0,1,2,3][4,5,6,7][8,9,10,11]

# (row, col)로 매칭됨
rows = np.array([0,1])
cols = np.array([2,3])

arr[:, arr[0]%2==0] # 모든 행(:)에서 짝수인 값이 저장된 컬럼만

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

### fancy indexing

정수 배열을 인덱스로 사용하는 방식
- 인덱스 위치를 직접 지정
- 순서 변경 가능
- 중복 선택 가능
- shape가 인덱스 배열을 따름

In [11]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[[0, 2, 4]])
# [10 30 50]

[10 30 50]


In [19]:
arr = np.arange(12).reshape(3,4) # [0,1,2,3][4,5,6,7][8,9,10,11]

# (row, col)로 매칭됨
rows = np.array([0,1])
cols = np.array([2,3])

print(arr[rows, cols])
# print(arr[[0,1], [2,3]]) # (0,2), (1,3)


[2 7]


In [37]:
arr = np.arange(12).reshape(3,4) # [0,1,2,3][4,5,6,7][8,9,10,11]

# (row, col)로 매칭됨
rows = np.array([0,1])
cols = np.array([2,3])

arr[:, :] # 그대로
arr[0, :] # 첫 번째 행만
arr[:, [0]] # 첫번째 컬럼만
arr[[0,1,2], [0]]  # 위와 동일

arr[:, [0, 1]] # 첫 번째와 두번째 컬럼만
arr[[0], [0]]  # [0][0]
arr[[0,1], [0,1]]  # [0][0]과 [1][1]

array([0, 5])

### boolean indexing vs. fancy indexing
- 둘 다 view가 아니라 copy를 만든다.
- Boolean indexing → “조건으로 거른다”
- Fancy indexing → “좌표 찍어서 뽑는다”

| 구분       | Boolean Indexing | Fancy Indexing  |
| -------- | ---------------- | --------------- |
| 기준       | True/False 조건    | 정수 인덱스 배열       |
| 목적       | 조건 필터링           | 위치 선택           |
| 중복 선택    | ❌                | ✅               |
| 순서 변경    | ❌                | ✅               |
| 결과 shape | 1차원 flatten      | 인덱스 배열 shape 따름 |


Boolean Indexing
1. 조건 mask 생성  
2. True 위치 linear scan  
3. 새로운 배열 생성  
→ 내부적으로 flatten 순회

Fancy Indexing  
1. 인덱스 배열 broadcast(필요시)
2. 각 좌표 계산  
3. 새로운 배열 생성   
→ 좌표 계산 기반 gather

## 1.9 유니버설 함수(ufunc)
- sin, cos, exp, log 같은 수학 함수도 배열 전체에 적용가능
- C언어로 처리되므로 빠름
- ufunc는 dtype 특화 C 루프 + stride 기반 포인터 연산 + SIMD 최적화 엔진

In [ ]:
np.sin(arr)  # 배열 각 요소에 sin 적용
np.exp(arr)  # 지수 함수 적용

array([   2.71828183,   20.08553692,  148.4131591 , 1096.63315843])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# 산술
print(np.add(arr, 10))      # [11 12 13 14]

# 삼각 함수
print(np.sin(arr))          # 각 요소의 sine

# 비교
print(np.greater(arr, 2))   # [False False  True  True]


[11 12 13 14]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[False False  True  True]


### 유니버설 함수 목록
https://numpy.org/doc/stable/reference/ufuncs.html?utm_source=chatgpt.com

### 1. 산술/기본 계산
- np.add : 요소별 덧셈
- np.subtract : 요소별 뺄셈
- np.multiply : 요소별 곱셈
- np.divide : 요소별 나눗셈
- np.true_divide
- np.floor_divide : 내림 나눗셈
- np.negative : 부호 변경
- np.logaddexp, np.logaddexp2 : 지수합 로그 계산

### 2. 삼각 함수
- np.sin, np.cos, np.tan
- np.arcsin, np.arccos, np.arctan
- np.sinh, np.cosh, np.tanh
- np.deg2rad, np.rad2deg
- np.hypot (직각삼각형 빗변계산)

### 3. 지수/로그
- np.exp, np.exp2
- np.log, np.log2, np.log10
- np.expm1, np.log1p (작은 값 처리를 위한 함수)

### 4. 비교/논리 연산
- np.equal, np.not_equal
- np.less, np.less_equal
- np.greater, np.greater_equal
- np.logical_and, np.logical_or, np.logical_not

### 5. 비트 연산
- np.bitwise_and, np.bitwise_or, np.bitwise_xor
- np.invert
- np.left_shift, np.right_shift

### 6. 집계/누적(Naive ufuncs는 아니지만 ufunc 메서드 제공)
- np.add.reduce, np.multiply.reduce
- np.logical_or.accumulate 등 ufunc의 .reduce, .accumulate, .reduceat, .outer 메서드

### 7. 기타
- np.sqrt, np.square : 제곱근/제곱
- np.remainder, np.mod : 나머지
- np.maximum, np.minimum : 요소별 최대/최소
- np.abs : 절대값
- np.sign : 부호 표시
- np.clip : 범위 clipping

### 파이썬 루프와 Numpy의 비교
- 파이썬 루프  
Python 인터프리터가 매번 loop  
매번 타입 체크  
매번 객체 생성  
<br>
- numpy  
1. dtype 확인  
2. contiguous 메모리 포인터 획득  
3. C for-loop 한 번  
4. SIMD 가능하면 벡터 명령어 사용(빠름) - 예를 들면 8개의 float를 한번에 더함

| Python   | NumPy      |
| -------- | ---------- |
| 객체 단위    | raw memory |
| 인터프리터 루프 | C 루프       |
| 매번 타입 체크 | 한 번만       |
| 분기 많음    | branch 최소  |


### ufunc 내부 구조 (핵심)  
ufunc 객체 안에는 이런 게 있다:
- loop table (dtype별 함수 포인터) - int32_add_loop, float64_add_loop 등
- type resolver
- broadcasting engine
- inner loop pointer


### 왜 NumPy ufunc는 GIL이 안 걸리나?
- Python 객체를 안 건드림
- refcount 변경 없음
- pure C 루프
- 실행 전에 GIL release


CPython은:
- reference counting 기반 GC
- 모든 객체가 refcount 필드 가짐
- 이 refcount는 thread-safe 아님

 "한 번에 한 스레드만 Python bytecode 실행 가능"  

 
그런데 numpy는 왜 빠져나가나?  
-> ufunc 실행 중에는 Python 객체를 안 만진다.

실행 흐름:

1. Python 레벨에서 np.add 호출  
2. dtype, shape 확인  
3. raw data pointer 획득  
4. GIL 해제  
5. C loop 실행  
6. GIL 다시 획득  
7. 결과 Python 객체 반환

In [ ]:
Py_BEGIN_ALLOW_THREADS # GIL release
    /* C 연산 */        # C 계산 중에는 다른 Python 스레드가 돌아갈 수 있다
Py_END_ALLOW_THREADS   # GIL acquired


IndentationError: unexpected indent (2292527488.py, line 2)

C 루프 안에서는:
- Python object 접근 안 함
- refcount 변경 없음
- 메모리 pointer만 이동
- dtype 고정  

즉 완전히 pure C numeric loop  
→ Python runtime 안전성 필요 없음

In [ ]:
import threading
import numpy as np

np.sin(big_arr) # 병렬 계산됨(C언어). 파이썬으로는 병렬처리 안됨.(thread-safe)
